// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Jun 01 14:28:23 2009

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef MAINFRAME_H
#define MAINFRAME_H


// begin wxGlade: ::extracode
// end wxGlade

class MyCanvas : public wxWindow
{
public:
	MyCanvas(wxWindow* parent, int id = wxID_ANY, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);
};


class MyFrame: public wxFrame {
public:
    // begin wxGlade: MyFrame::ids
    // end wxGlade

    MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MyFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MyFrame::attributes
    MyCanvas* m_stCanvas;
    wxMenuBar* m_stMainMenu;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnMenuFileExit(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // MAINFRAME_H
