// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Jun 01 14:28:23 2009

#include "MainFrame.h"

// begin wxGlade: ::extracode
// end wxGlade

MyCanvas::MyCanvas(wxWindow *parent, int id, const wxPoint &pos, const wxSize &size, long style)
: wxWindow(parent, id, pos, size, style)
{
}


MyFrame::MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: MyFrame::MyFrame
    m_stCanvas = new MyCanvas(this, wxID_ANY);
    m_stMainMenu = new wxMenuBar();
    wxMenu* wxglade_tmp_menu_1 = new wxMenu();
    wxglade_tmp_menu_1->Append(wxID_ANY, wxT("E&xit"), wxEmptyString, wxITEM_NORMAL);
    m_stMainMenu->Append(wxglade_tmp_menu_1, wxT("&File"));
    SetMenuBar(m_stMainMenu);

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(MyFrame, wxFrame)
    // begin wxGlade: MyFrame::event_table
    EVT_MENU(wxID_ANY, MyFrame::OnMenuFileExit)
    // end wxGlade
END_EVENT_TABLE();


void MyFrame::OnMenuFileExit(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (MyFrame::OnMenuFileExit) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add MyFrame event handlers


void MyFrame::set_properties()
{
    // begin wxGlade: MyFrame::set_properties
    SetTitle(wxT("MainFrame"));
    SetSize(wxSize(521, 443));
    // end wxGlade
}


void MyFrame::do_layout()
{
    // begin wxGlade: MyFrame::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    sizer_1->Add(m_stCanvas, 1, wxEXPAND, 0);
    SetSizer(sizer_1);
    Layout();
    // end wxGlade
}



class MyApp: public wxApp {
public:
    bool OnInit();
};

IMPLEMENT_APP(MyApp)

bool MyApp::OnInit()
{
    wxInitAllImageHandlers();
    MyFrame* MainFrame = new MyFrame(NULL, wxID_ANY, wxEmptyString);
    SetTopWindow(MainFrame);
    MainFrame->Show();
    return true;
}




