// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Mar 30 22:19:04 2009
#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef TEMP_H
#define TEMP_H


#include <string>
#include "ModelObject.h"

// begin wxGlade: ::extracode
// end wxGlade

const int IDB_BROWSE	=	101;
const int IDB_TEST_1	=	102;
const int IDB_TEST_2	=	103;
const int IDB_TEST_3	=	104;
const int IDB_TEST_4	=	105;

class MyFrame: public wxFrame {
public:
    // begin wxGlade: MyFrame::ids
    // end wxGlade

    MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MyFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MyFrame::attributes
    wxStaticText* label_1;
    wxTextCtrl* m_editFileName;
    wxButton* m_btnBrowse;
    wxPanel* panel_1;
    wxButton* m_btnTest1;
    wxButton* button_3;
    wxButton* button_4;
    wxButton* button_5;
    wxPanel* panel_2;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnBtnBrowse(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnTest1(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnTest2(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnTest3(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnTest4(wxCommandEvent &event); // wxGlade: <event_handler>
private:
	CModelObject _obj;
	std::wstring _file;
}; // wxGlade: end class


#endif // TEMP_H
