// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Mar 30 22:19:04 2009


#include "Test.h"

// begin wxGlade: ::extracode
// end wxGlade



MyFrame::MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxCAPTION|wxCLOSE_BOX|wxSYSTEM_MENU|wxSIMPLE_BORDER)
{
    // begin wxGlade: MyFrame::MyFrame
    label_1 = new wxStaticText(this, wxID_ANY, wxT("M2 File:"), wxDefaultPosition, wxDefaultSize, wxALIGN_RIGHT);
    m_editFileName = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    m_btnBrowse = new wxButton(this, IDB_BROWSE, wxT("&Browse"));
    panel_1 = new wxPanel(this, wxID_ANY);
    m_btnTest1 = new wxButton(this, IDB_TEST_1, wxT("Test &1"));
    button_3 = new wxButton(this, IDB_TEST_2, wxT("Test &2"));
    button_4 = new wxButton(this, IDB_TEST_3, wxT("Test &3"));
    button_5 = new wxButton(this, IDB_TEST_4, wxT("Test &4"));
    panel_2 = new wxPanel(this, wxID_ANY);

    set_properties();
    do_layout();
    // end wxGlade
}

void MyFrame::do_layout()
{
    // begin wxGlade: MyFrame::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_1_copy = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    sizer_2->Add(label_1, 0, wxALIGN_CENTER_VERTICAL, 0);
    sizer_2->Add(m_editFileName, 1, wxEXPAND, 0);
    sizer_2->Add(m_btnBrowse, 0, 0, 0);
    sizer_1_copy->Add(sizer_2, 0, wxALL|wxEXPAND, 4);
    sizer_3->Add(panel_1, 1, wxEXPAND, 0);
    sizer_3->Add(m_btnTest1, 0, 0, 0);
    sizer_3->Add(button_3, 0, 0, 0);
    sizer_3->Add(button_4, 0, 0, 0);
    sizer_3->Add(button_5, 0, 0, 0);
    sizer_3->Add(panel_2, 1, wxEXPAND, 0);
    sizer_1_copy->Add(sizer_3, 0, wxALL|wxEXPAND, 4);
    sizer_1->Add(sizer_1_copy, 1, wxEXPAND, 0);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    Layout();
	Center();
    // end wxGlade
}


BEGIN_EVENT_TABLE(MyFrame, wxFrame)
    // begin wxGlade: MyFrame::event_table
    EVT_BUTTON(IDB_BROWSE, MyFrame::OnBtnBrowse)
    EVT_BUTTON(IDB_TEST_1, MyFrame::OnBtnTest1)
    EVT_BUTTON(IDB_TEST_2, MyFrame::OnBtnTest2)
    EVT_BUTTON(IDB_TEST_3, MyFrame::OnBtnTest3)
    EVT_BUTTON(IDB_TEST_4, MyFrame::OnBtnTest4)
    // end wxGlade
END_EVENT_TABLE();


void MyFrame::OnBtnBrowse(wxCommandEvent &event)
{
	wxFileDialog dlg(this,
						wxT("Open M2 File.."),
						wxEmptyString,
						_T("*.m2"),
						_T("M2 Files (*.m2)|*.m2|All Files (*.*)|*.*"),
						wxFD_OPEN|wxFD_FILE_MUST_EXIST);
	if (dlg.ShowModal() == wxID_OK)
	{
		m_editFileName->SetValue(dlg.GetPath());
	}

    event.Skip();}


void MyFrame::OnBtnTest1(wxCommandEvent &event)
{
	//char ch[1024];
	//strcpy(ch, (const char*)m_editFileName->GetValue().mb_str(wxConvUTF8));

	_obj.Init(L"E:\\DATA", L"D:\\Studio\\DeWModel\\Apps\\wxDeMPQ\\DBCFields.xml", L"D:\\Studio\\DeWModel\\Apps\\wxDeMPQ\\DBCFields.xml");
	_file = L"e:\\data\\ArrowAcidFlight_01.m2";

	_obj.LoadModel(L"e:\\Data\\common-2.MPQ", "ITEM\\OBJECTCOMPONENTS\\AMMO\\ArrowAcidFlight_01.m2");

    event.Skip();
}


void MyFrame::OnBtnTest2(wxCommandEvent &event)
{
	std::wstring file = _file + L".x";
	int i = _obj.ToXFile(file);
	if(i != 0)
	{
	}

    event.Skip();
    wxLogDebug(wxT("Event handler (MyFrame::OnBtnTest2) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void MyFrame::OnBtnTest3(wxCommandEvent &event)
{
//	_obj.Init(L"E:\\DATA");

    event.Skip();
    wxLogDebug(wxT("Event handler (MyFrame::OnBtnTest3) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void MyFrame::OnBtnTest4(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (MyFrame::OnBtnTest4) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add MyFrame event handlers


void MyFrame::set_properties()
{
    // begin wxGlade: MyFrame::set_properties
    SetTitle(wxT("M2 Test"));
    SetBackgroundColour(wxSystemSettings::GetColour(wxSYS_COLOUR_3DFACE));
    // end wxGlade
}



class MyApp: public wxApp {
public:
    bool OnInit();
};

IMPLEMENT_APP(MyApp)

bool MyApp::OnInit()
{
    wxInitAllImageHandlers();
    MyFrame* frame_1 = new MyFrame(NULL, wxID_ANY, wxEmptyString);
    SetTopWindow(frame_1);
    frame_1->Show();
    return true;
}
