// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Jun 08 11:33:11 2009

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef TESTOUTPUT_H
#define TESTOUTPUT_H


// begin wxGlade: ::extracode
// end wxGlade


const int ID_CB_DEBUG		=	101;
const int ID_CB_INFO		=	102;
const int ID_CB_WARN		=	104;
const int ID_CB_ERROR		=	108;

class COutput;

class MyFrame: public wxFrame {
public:
    // begin wxGlade: MyFrame::ids
    // end wxGlade

    MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MyFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MyFrame::attributes
    wxStaticBox* sizer_4_staticbox;
    wxCheckBox* m_cbDEBUG;
    wxCheckBox* m_cbINFO;
    wxCheckBox* m_cbWARN;
    wxCheckBox* m_cbERROR;
    wxTextCtrl* m_textInfo;
    wxButton* button_1;
    wxTextCtrl* m_textOutput;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnCheckBoxLevel(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnButtonOutput(wxCommandEvent &event); // wxGlade: <event_handler>
private:
	COutput *_output;
}; // wxGlade: end class


#endif // TESTOUTPUT_H
