// -*- C++ -*- generated by wxGlade 0.6.3 on Fri May 15 18:40:59 2009

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade


#ifndef MAINFRAME_H
#define MAINFRAME_H


// begin wxGlade: ::extracode
// end wxGlade


class MyFrame: public wxFrame {
public:
    // begin wxGlade: MyFrame::ids
    // end wxGlade

    MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MyFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MyFrame::attributes
    wxStaticText* label_3;
    wxTextCtrl* m_editMPQ;
    wxStaticText* label_4;
    wxTextCtrl* m_editDBC;
    wxStaticText* label_5;
    wxTextCtrl* m_editWDB;
    wxRadioButton* m_radioDBC;
    wxRadioButton* m_radioWDB;
    wxStaticLine* static_line_1;
    wxStaticText* label_1;
    wxStaticText* label_6;
    wxTextCtrl* m_editQueryPos;
    wxStaticText* label_7;
    wxTextCtrl* m_editQueryType;
    wxStaticText* label_8;
    wxTextCtrl* m_editQueryValue;
    wxStaticLine* static_line_3;
    wxStaticText* label_2;
    wxStaticText* label_9;
    wxTextCtrl* m_editResultPos;
    wxStaticText* label_10;
    wxTextCtrl* m_editResultType;
    wxStaticText* label_11;
    wxTextCtrl* m_editResultValue;
    wxStaticLine* static_line_2;
    wxButton* m_btnClose;
    wxPanel* panel_1;
    wxButton* m_btnQuery;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnRadioDBC(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnRadioWDB(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnClose(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnQuery(wxCommandEvent &event); // wxGlade: <event_handler>
private:
	int DBCQuery();
	int WDBQuery();

	wxString Field2Str(int type) const;
	wxString ResultField2Str(const TResultData& data, wxString& value) const;
}; // wxGlade: end class


#endif // MAINFRAME_H
